#!/bin/sh

echo "Last reboot time: $(date)\n" >> reboot.logs

# Função para limpar volumes que não começam com "jgomes"
clean_volumes() {
  # Lista todos os volumes
  all_volumes=$(docker volume ls -q)

cd my/jgomes
docker compose down

  # Itera sobre cada volume
  for volume in $all_volumes
  do
    # Obtém o nome do volume
    volume_name=$(docker volume inspect --format '{{.Name}}' $volume)

    # Verifica se o nome do volume não começa com "jgomes"
    if ! echo "$volume_name" | grep -q "^jgomes"; then
      # Remove o volume
      echo "Removendo volume: $volume_name"
      docker volume rm $volume
    fi
  done
  ./kill_docker_ports.sh
  docker compose up -d
cd ../../
  echo "Docker ready : $(date)\n" >> reboot.logs
}

sleep 120

# Chama a função para limpar volumes
clean_volumes

-------------------------
crontab -e

@reboot sh /home/jgomes/reboot_script.sh
