version: "3.9"
services:
    mysql:
        container_name: jgomes_site_dev_mysql
        build: './mysql'
        env_file:
            - .env
        ports:
            - "3406:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        volumes:
            - dbData:/var/lib/mysql

    phpmyadmin:
        container_name: jgomes_site_dev_phpmyadmin
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64  # Forces the platform to amd64
        env_file:
            - .env
        ports:
            - "8092:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ALLOW_EMPTY_PASSWORD: yes

    rabbitmq:
        container_name: jgomes_site_dev_rabbit
        build:
            context: './rabbitmq'
        env_file:
            - .env
        ports:
            - "5673:5672"
            - "15673:15672"
        environment:
            -  RABBITMQ_USER=${RABBIT_USER}
            -  RABBITMQ_PASSWORD=${RABBIT_PASS}
            -  RABBITMQ_DEFAULT_USER=${RABBIT_USER}
            -  RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}

    redis:
        container_name: jgomes_site_dev_redis
        restart: always
        build: './redis'
        volumes:
            - redis:/var/lib/redis
            - dbRedis:/data
        ports:
            - "6378:6378"
        networks:
            - redis-network

    redis-commander:
        container_name: jgomes_site_dev_redis-commander
        build: './redis-commander'
        platform: linux/amd64  # Forces the platform to amd64
        restart: always
        ports:
            - "8082:8081"
        networks:
            - redis-network
        depends_on:
            - redis
        environment:
            - REDIS_HOSTS=${REDIS_HOSTS}
            - HTTP_USER=${REDIS_USER}
            - HTTP_PASSWORD=${REDIS_PASS}
networks:
    redis-network:
        driver: bridge
volumes:
    dbData:
    dbRedis:
    redis:
