version: "3.9"
services:
    mysql:
        container_name: jgomes_site_dev_mysql
        build: './mysql'
        env_file:
            - .env
        ports:
            - "3406:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        volumes:
            - dbData:/var/lib/mysql

    phpmyadmin:
        container_name: jgomes_site_dev_phpmyadmin
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64  # Forces the platform to amd64
        env_file:
            - .env
        ports:
            - "8090:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ALLOW_EMPTY_PASSWORD: yes

    rabbitmq:
        container_name: jgomes_site_dev_rabbit
        build:
            context: './rabbitmq'
        env_file:
            - .env
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        container_name: jgomes_site_dev_redis
        restart: always
        image: redis:latest
        ports:
            - "6379:6379"
        command: [ "redis-server", "--appendonly", "yes" ]
        volumes:
            - redisData:/data

    redis-commander:
        build:
            context: './redis-commander'
        env_file:
            - .env
        platform: linux/amd64  # Forces the platform to amd64
        container_name: jgomes_site_dev_redis_commander
        restart: always
        ports:
            - "8085:8081"
        depends_on:
            - redis
volumes:
    dbData:
    redisData:
