# redis-commander base image
FROM rediscommander/redis-commander:latest

# Defined here the env vars ( Not workig here. Defined at docker-compose )
#ENV REDIS_HOSTS=${REDIS_HOSTS}
#ENV HTTP_USER ${REDIS_USER}
#ENV HTTP_PASSWORD ${REDIS_PASS}

# Port expose
EXPOSE 8081
