version: "3.9"
services:
    mysql:
        container_name: jgomes_site_test_mysql
        build: './mysql'
        ports:
            - "3405:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        volumes:
            - dbData:/var/lib/mysql
        networks:
            - jgomes-site_test-docker

    phpmyadmin:
        container_name: jgomes_site_test_phpmyadmin
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64  # Forces the platform to amd64
        ports:
            - "8095:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        networks:
            - jgomes-site_test-docker

    rabbitmq:
        container_name: jgomes_site_test_rabbit
        build:
            context: './rabbitmq'
        ports:
            - "5675:5672"
            - "15675:15672"
        networks:
            - jgomes-site_test-docker
volumes:
    dbData:

networks:
    jgomes-site_test-docker:
